### ISSUE TITLE
NPC: Oma reagiert auf Müll aufheben- und fallen lassen

### ISSUE THREAD

**Issue by longarmin** [longarmin/GameJamDoMai20#6]
Ziel ist hier erst einmal ein Text in Omas Sprechblase:

- "Vielen Dank, dass Sie den Müll der anderen Mieter wegräumen"
- "Was fällt Ihnen ein, Ihren Müll im Treppenhaus zu platzieren?"

**Comment by Tazora** [comment]
Fähigkeit der Oma

- Datenbank hinterlegt -> Karma der Charaktere wird gespeichert
